os:
  - linux

language: python

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels http://conda.binstar.org/heimdali
  - conda update conda
  - conda install conda-build
  - conda info -a

install:
  - conda build --no-test conda-recipe

script:
  - conda install --use-local simudiff
  - cd simudiff/test
  - python test_case.py
  - python test_comparer.py
