package:
  name: simudiff
  version: 0.0.4

source:
  path: ..
  #fn: 0.0.4.tar.gz
  #url: https://github.com/dfroger/simudiff/archive/0.0.4.tar.gz

build:
  number: 0

requirements:
  build:
    - python 2.7*
    - setuptools
    - numpy
  run:
    - python 2.7*
    - numpy

test:
  files:
    - ../simudiff/test/test_case.py
    - ../simudiff/test/test_comparer.py
  requires:
    - python 2.7*
  commands:
    - python test_case.py
    - python test_comparer.py

about:
  home: https://github.com/dfroger/simudiff
  license: GPL
