package:
  name: arrayequal
  version: 0.1.0

source:
  fn: 0.1.0.tar.gz
  url: https://github.com/dfroger/arrayequal/archive/0.1.0.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  files:
    - ../arrayequal/test/test_case.py
    - ../arrayequal/test/test_comparer.py
  requires:
    - python
  commands:
    - python test_case.py
    - python test_comparer.py

about:
  home: https://github.com/dfroger/arrayequal
  license: GPL
  summary: Test for numpy array equality
